// <auto-generated />
namespace Mensageiro.Repositorios.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdicionarEntidadeConversa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionarEntidadeConversa));
        
        string IMigrationMetadata.Id
        {
            get { return "201810160025218_AdicionarEntidadeConversa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
